module.exports = async schema => {
  if (await schema.hasTable('usuarios'))
    schema.createTable('usuarios', t => {
      t.string('nome')
    })
  if (await schema.hasTable('acolhidos'))
    schema.createTable('acolhidos', t => {
      t.string('nome')
      t.date('nascimento')
      t.string('mae')
      t.string('pai')
      t.string('rg')
      t.string('cpf')
      t.string('estado_civil')
      t.string('de_onde')
      t.string('para_onde')
      t.integer('tempo_na_rua')
      t.string('motivo')
      t.string('religiao')
      t.boolean('batismo')
      t.boolean('primeira_comunhao')
      t.boolean('crisma')
      t.dateTime('entrada')
      t.dateTime('saida')
      t.dateTime('cadastrado_em')
      t.integer('usuario_id')
    })
  if (await schema.hasTable('enderecos'))
    schema.createTable('enderecos', t => {
      t.integer('acolhido_id')
      t.string('logradouro')
      t.string('numero')
      t.string('complemento')
      t.string('bairro')
      t.string('cidade')
      t.string('uf')
    })
  if (await schema.hasTable('telefones'))
    schema.createTable('telefones', t => {
      t.integer('acolhido_id')
      t.string('ddd')
      t.string('numero')
      t.boolean('celular')
    })
  if (await schema.hasTable('saude'))
    schema.createTable('saude', t => {
      t.integer('acolhido_id')
      t.string('sus')
      t.integer('ultima_consulta_ha')
      t.boolean('convulsoes')
    })
  if (await schema.hasTable('medicamentos'))
    schema.createTable('medicamentos', t => {
      t.integer('saude_id')
      t.string('nome')
    })
  if (await schema.hasTable('vicios'))
    schema.createTable('vicios', t => {
      t.integer('acolhido_id')
      t.string('substancia')
    })
  if (await schema.hasTable('policial'))
    schema.createTable('policial', t => {
      t.integer('acolhido_id')
      t.integer('tempo_preso')
      t.string('artigo')
    })
  if (await schema.hasTable('pertences'))
    schema.createTable('pertences', t => {
      t.integer('acolhido_id')
      t.string('descricao')
    })
  if (await schema.hasTable('servicos'))
    schema.createTable('servicos', t => {
      t.integer('refeicoes')
      t.integer('banhos')
      t.integer('sabonetes')
      t.integer('barbeadores')
    })
}
